name: chat_app_sync
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#ui
  flutter_screenutil: ^5.6.0
  flutter_easyloading: ^3.0.5
  infinite_scroll_pagination: ^3.2.0
#icon
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
#manage state
  get: ^4.6.5
#api
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  get_storage: ^2.0.3
  flutter_secure_storage: ^6.0.0
#sqlite
  sqflite:
#workmanager
  workmanager: ^0.5.1
  cached_network_image: ^3.2.3
  socket_io_client: ^2.0.1
dev_dependencies:
#test
  flutter_test:
    sdk: flutter
#rule
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/login_background.jpg
    - assets/images/avatar.jpeg
    #alert_dialog_icon
    - assets/images/illustration/warning_icon.png
    - assets/images/illustration/error_icon.png
    - assets/images/illustration/success_icon.png
  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
  